/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class ConsultaExpedientes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaExpedientes
     */
    public ConsultaExpedientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-SIH-ISSSTEico1_phixr1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 20, 186, 200);

        jLabel2.setText("Consulta de Expedientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 280, 17);

        jLabel3.setText("RFC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 26, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 50, 190, 27);

        jLabel4.setText("Presion Arterial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 140, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 220, 160, 27);

        jLabel5.setText("Temperatura");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 230, 100, 17);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(500, 220, 150, 27);

        jLabel6.setText("Tipo de Sangre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 130, 17);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 280, 160, 27);

        jLabel7.setText("Frecuencia Cardiaca");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 290, 150, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(500, 280, 150, 27);

        jButton1.setText("Consultar");
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 100, 100, 29);

        jLabel8.setText("Frecuencia Respiratoria");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 330, 170, 17);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(160, 360, 160, 27);

        jLabel9.setText("Perimetro Abdominal");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 330, 160, 17);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(500, 360, 150, 27);

        jButton2.setText("Regresar");
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 460, 110, 29);

        jLabel10.setText("Expediente");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 50, 90, 17);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(470, 50, 140, 27);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 170, 660, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaExpedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
