/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class Expedientes extends javax.swing.JFrame {

    /**
     * Creates new form Expedientes
     */
    public Expedientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDiag = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFarmaco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPronostico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Padecimiento Actual");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 158, 47);
        getContentPane().add(txtPad);
        txtPad.setBounds(20, 70, 320, 40);

        jLabel2.setText("Diagnóstico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 110, 17);

        txaDiag.setColumns(20);
        txaDiag.setRows(5);
        jScrollPane1.setViewportView(txaDiag);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 590, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-SIH-ISSSTEico1_phixr1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 0, 210, 210);

        jLabel4.setText("Fármaco Recomendado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 350, 190, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1461751083_Stethoscope_Black.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 360, 130, 130);
        getContentPane().add(txtFarmaco);
        txtFarmaco.setBounds(40, 390, 210, 27);

        jLabel6.setText("Pronóstico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 340, 130, 17);
        getContentPane().add(txtPronostico);
        txtPronostico.setBounds(380, 370, 210, 50);

        jButton1.setText("Aceptar");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 470, 67, 29);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 470, 74, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDiag;
    private javax.swing.JTextField txtFarmaco;
    private javax.swing.JTextField txtPad;
    private javax.swing.JTextField txtPronostico;
    // End of variables declaration//GEN-END:variables
}
