
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class RegistroSignos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroSignos
     */
    public RegistroSignos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRFCD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbSangre = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtPresion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        txtFrCard = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFrR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPerTorax = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPerAbdom = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNumExp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPerCef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/abril/Descargas/1460409032_pencil.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 10, 128, 128);

        jLabel2.setBackground(new java.awt.Color(16, 13, 9));
        jLabel2.setForeground(new java.awt.Color(4, 2, 2));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whynot.jpg"))); // NOI18N
        jLabel2.setText("Regis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 530, 20);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 0, 0));
        jLabel3.setText("Registro de Datos Básicos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 310, 40);

        jLabel4.setText("RFC Derechohabiente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 190, 50);

        jLabel5.setText("Tipo de Sangre ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 150, 120, 17);

        txtRFCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCDActionPerformed(evt);
            }
        });
        getContentPane().add(txtRFCD);
        txtRFCD.setBounds(210, 80, 160, 30);

        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 160, 70, 17);

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha);
        txtFecha.setBounds(520, 150, 160, 30);

        jLabel7.setText("Hora");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(710, 150, 50, 17);
        getContentPane().add(txtHora);
        txtHora.setBounds(760, 140, 160, 27);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(30, 570, 120, 40);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1459970446_button_cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(200, 570, 130, 40);

        cmbSangre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el tipo de Sangre", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "" }));
        cmbSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSangreActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSangre);
        cmbSangre.setBounds(210, 150, 160, 27);

        jLabel8.setText("Estatura");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 300, 70, 30);

        txtEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstaturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstatura);
        txtEstatura.setBounds(110, 300, 160, 27);

        jLabel9.setText("Peso");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 350, 60, 30);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(110, 350, 160, 27);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 240, 790, 10);

        jLabel10.setText("Presion Arterial");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 290, 120, 30);
        getContentPane().add(txtPresion);
        txtPresion.setBounds(460, 290, 130, 30);

        jLabel11.setText("IMC");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 350, 90, 17);
        getContentPane().add(txtIMC);
        txtIMC.setBounds(460, 340, 130, 27);

        jLabel12.setText("Somatometría");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 260, 140, 30);

        jLabel13.setText("Edad");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 200, 35, 17);

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(210, 200, 160, 27);

        jLabel14.setText("Temperatura");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(610, 290, 100, 30);

        jLabel15.setText("Frecuencia Card");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(610, 340, 120, 17);
        getContentPane().add(txtTemp);
        txtTemp.setBounds(750, 290, 150, 27);
        getContentPane().add(txtFrCard);
        txtFrCard.setBounds(750, 330, 150, 27);

        jLabel16.setText("Frecuencia Respiratoria");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 400, 170, 17);
        getContentPane().add(txtFrR);
        txtFrR.setBounds(110, 430, 160, 27);

        jLabel17.setText("Perímetro Torácico");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 400, 140, 17);
        getContentPane().add(txtPerTorax);
        txtPerTorax.setBounds(460, 420, 130, 27);

        jLabel18.setText("Perímetro Abdominal");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 480, 160, 17);
        getContentPane().add(txtPerAbdom);
        txtPerAbdom.setBounds(110, 510, 160, 27);

        jLabel19.setText("Num. Expediente");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(390, 200, 130, 20);
        getContentPane().add(txtNumExp);
        txtNumExp.setBounds(520, 200, 160, 27);

        jLabel20.setText("Perimetro Cefalico");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(590, 390, 140, 17);
        getContentPane().add(txtPerCef);
        txtPerCef.setBounds(750, 410, 150, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSangreActionPerformed
        TDA_Expedientes fu=new TDA_Expedientes();
        fu.setSangre((String)cmbSangre.getSelectedItem());
        fu.setRfc(txtRFCD.getText());
        fu.registrarExpediente();
    }//GEN-LAST:event_cmbSangreActionPerformed

    private void txtEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstaturaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        TDA_Expedientes te=new TDA_Expedientes();
        
        te.setFecha(txtFecha.getText());
        te.setHora(txtHora.getText());
        te.setEdad(Integer.parseInt(txtEdad.getText()));
        te.setNumExp((txtNumExp.getText()));
        te.setEstatura(txtEstatura.getText());
        te.setPeso(txtPeso.getText());
        te.setFrecuenciaC(txtFrCard.getText());
        te.setFrecuenciaR(txtFrR.getText());
        te.setIMC(txtIMC.getText());
        te.setPresion(txtPresion.getText());
        te.setTemp(txtTemp.getText());
        te.setPerAb(txtPerAbdom.getText());
        te.setPerTor(txtPerTorax.getText());
        
        te.registrarHistorial();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        try{    
        int edad=Integer.parseInt(txtEdad.getText());
           if(edad > 0 && edad < 4){
          txtPerTorax.setEnabled(true);
          txtPerCef.setEnabled(true);
          txtPresion.setEnabled(false);
        }else {
            txtPerTorax.setEnabled(false);
            txtPerCef.setEnabled(false);
            txtPresion.setEnabled(true);
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese la edad");
        }
    }//GEN-LAST:event_txtEdadKeyReleased

    private void txtRFCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCDActionPerformed
                                
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroSignos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroSignos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroSignos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroSignos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroSignos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cmbSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFrCard;
    private javax.swing.JTextField txtFrR;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtNumExp;
    private javax.swing.JTextField txtPerAbdom;
    private javax.swing.JTextField txtPerCef;
    private javax.swing.JTextField txtPerTorax;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPresion;
    private javax.swing.JTextField txtRFCD;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
